# Generated by Django 4.2.30 on 2026-04-27 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('currency', 'Currency'), ('index', 'Index')], max_length=20)),
                ('subcategory', models.CharField(blank=True, choices=[('deriv', 'Deriv'), ('weltrade', 'Weltrade')], max_length=50, null=True)),
                ('result', models.CharField(blank=True, choices=[('win', 'Win'), ('lose', 'Lose'), ('breakeven', 'Breakeven')], max_length=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('pnl', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_trade',
                'ordering': ['-date'],
            },
        ),
    ]
