# Generated by Django 4.2.30 on 2026-04-29 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_instrumentcategory_platform_alter_trade_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelTable(
            name='trade',
            table='api_trade',
        ),
    ]
