# Generated by Django 4.2.30 on 2026-05-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trade',
            name='pair',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trade',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
