# Generated by Django 4.2.30 on 2026-05-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trade_category_trade_pair_trade_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='risk_percent',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='balance',
            name='target_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
