# Generated by Django 4.2.30 on 2026-05-03 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_balance_risk_percent_balance_target_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_notes', to='api.trade')),
            ],
        ),
    ]
