# Generated by Django 4.2.30 on 2026-05-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tradenote'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trade',
            table=None,
        ),
    ]
