# Generated by Django 4.2.30 on 2026-05-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_trade_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='lots',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='swap',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
