# Generated by Django 4.2.30 on 2026-05-04 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_trade_commission_trade_lots_trade_swap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='lots',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='swap',
        ),
    ]
