# Generated by Django 4.2.30 on 2026-05-04 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_trade_commission_remove_trade_lots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='amount',
        ),
        migrations.AddField(
            model_name='balance',
            name='last_reset_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='balance',
            name='starting_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
