# Generated by Django 4.2.30 on 2026-06-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='subcategory',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
